### ISSUE TITLE
Release `teal.logger` to CRAN

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.logger#51]
### Summary
The objective is to make teal.code available on CRAN. However, a preliminary release is necessary due to ongoing updates up to this point.

### Acceptance Criteria
* [X] Update README as directed [here](https://github.com/insightsengineering/coredev-tasks/issues/462)
* [X] Group vignettes in a meaningful cohorts as directed [here](https://github.com/insightsengineering/coredev-tasks/issues/468)
* [X] Add/Confirm the `--as-cran` option in CICD pipeline
* [x] R CMD Check passed or create new issue to fix
* [x] Release `teal.logger` (full version bump and git tag)
* [x] Push to CRAN

**Comment by donyunardi** [comment]
r-universe looks good:
![image](https://github.com/insightsengineering/teal.logger/assets/8597300/9c0ca983-65d4-41d6-b392-08ef1b12f0c1)

Uploaded to CRAN and waiting for @gogonzo confirmation:
![image](https://github.com/insightsengineering/teal.logger/assets/8597300/bf8fdbc2-3e48-4f71-9081-313f37801dab)

**Comment by gogonzo** [comment]
Confirmed. Let's wait for the response from the CRAN team now

**Comment by gogonzo** [comment]
> on its way to CRAN.

**Comment by m7pr** [comment]
Was 'on its way to CRAN' a reviewers reply? Great news!

**Comment by gogonzo** [comment]
![image](https://github.com/insightsengineering/teal.logger/assets/6959016/5dbd6a6d-71aa-45c1-bc46-fa61a48a2a92)
