### ISSUE TITLE
Fix CRAN issues

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.logger#58]
Please use only undirected quotation marks in the description text.
e.g. `teal` --> 'teal'

Please do not start the description with "This package", package name,
title or similar.

The Description field is intended to be a (one paragraph) description of
what the package does and why it may be useful. Please add more details
about the package functionality and implemented methods in your
Description text.

The LICENSE file is only needed if you have additional restrictions to
the license which you have not? In that case omit the file and its
reference in the DESCRIPTION file.

Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'teal'
Please note that package names are case sensitive.

\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user. Does not seem necessary.
Please replace \dontrun with \donttest.

Please fix and resubmit.

**Comment by gogonzo** [comment]
> on its way to CRAN.

**Comment by m7pr** [comment]
https://cran.r-project.org/web/packages/teal.logger/index.html
