### ISSUE TITLE
[Question]: Should we consider re-exporting all functions from `{logger}` in `{teal.logger}` so that we can avoid having both in all packages.

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.logger#74]
Initially asked by @averissimo here https://github.com/insightsengineering/teal.modules.clinical/issues/618#issuecomment-1911825071

**Comment by pawelru** [comment]
We might consider add it `Depends` instead of re-export.

**Comment by m7pr** [comment]
We use `logger` heavily. Why we also need to use it in other packages if we import `teal.logger` in there?

**Comment by pawelru** [comment]
> We use logger heavily. Why we also need to use it in other packages if we import teal.logger in there?

This is a valid concern.

Please have a look at https://github.com/insightsengineering/coredev-tasks/issues/502 and associated (still draft) PR: https://github.com/insightsengineering/teal.logger/pull/73. I think it's highly connected. I believe that after this, the usage of logger functionalities will be very limited if not none (in extreme case). A developer will be advised to use base message / warning / stop instead. (Let's just try not to discuss the details here to keep the discussion well organised)

Implementation wise, re: my last comment:
If we are talking about literally *all* function then Depends seems to be more preferable. But I guess you only mean `log_xyz` (e.g. `log_info()`, `log_warn()`) and in such case re-export will be more clean.

**Comment by m7pr** [comment]
got it, thanks

**Comment by gogonzo** [comment]
Closing this up as we were never really fans of re-exporting anything. Currently in downstrem packages we use `logger::log_trace` only, `message` and `warning` are fetched by `teal.logger::register_handlers`
