### ISSUE TITLE
[Bug]: log_shiny_input_changes checks for session_proxy but session is ShinySession

### ISSUE THREAD

**Issue by llrs-roche** [insightsengineering/teal.logger#98]
### What happened?

When running interactively the example of `log_shiny_input_changes` I got an error message:

```r
Warning: Error in log_shiny_input_changes: inherits(session, "session_proxy") is not TRUE
  44: <Anonymous>
  43: stop
  42: stopifnot
  41: log_shiny_input_changes [C:/Users/sanchosl/AppData/Local/Temp/Rtmp2Z3KZu/R.INSTALL7ebc330b4754/teal.logger/R/log_shiny_input_changes.R#47]
  40: server [#2]
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Error in log_shiny_input_changes(input, excluded_inputs = "password",  : 
  inherits(session, "session_proxy") is not TRUE
```

The check is testing for `session_proxy `but session is a `ShinySession`. Simply changing that would probably solve the issue (I don't see any mention in shiny about a session_proxy class). 

`logger::log_shiny_input_changes` checks for `session_proxy` too but there are some other checks and their example doesn't fail. The other checks:

```
(shiny::isRunning() || inherits(session, "MockShinySession") || 
        inherits(session, "session_proxy"))
``` 

### sessionInfo()

```R
─ Session info ────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14 ucrt)
 os       Windows 11 x64 (build 22631)
 system   x86_64, mingw32
 ui       RStudio
 language en
 collate  Spanish_Spain.utf8
 ctype    Spanish_Spain.utf8
 tz       Europe/Madrid
 date     2024-11-06
 rstudio  2024.09.0+375 Cranberry Hibiscus (desktop)
 pandoc   3.5 @ C:\\Users\\sanchosl\\AppData\\Local\\Pandoc\\pandoc.exe

─ Packages ────────────────────────────────────────────────────────────────────
 ! package     * version    date (UTC) lib source
   brio          1.1.5      2024-04-24 [1] CRAN (R 4.4.1)
   bslib         0.8.0      2024-07-29 [1] CRAN (R 4.4.1)
   cachem        1.1.0      2024-05-16 [1] CRAN (R 4.4.1)
   cli           3.6.3      2024-06-21 [1] CRAN (R 4.4.1)
   crayon        1.5.3      2024-06-20 [1] CRAN (R 4.4.1)
   desc          1.4.3      2023-12-10 [1] CRAN (R 4.4.1)
   devtools    * 2.4.5      2022-10-11 [1] CRAN (R 4.4.1)
   digest        0.6.37     2024-08-19 [1] CRAN (R 4.4.1)
   ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.4.1)
   fansi         1.0.6      2023-12-08 [1] CRAN (R 4.4.1)
   fastmap       1.2.0      2024-05-15 [1] CRAN (R 4.4.1)
   fs            1.6.4      2024-04-25 [1] CRAN (R 4.4.1)
   glue          1.8.0      2024-09-30 [1] CRAN (R 4.4.1)
   htmltools     0.5.8.1    2024-04-04 [1] CRAN (R 4.4.1)
   htmlwidgets   1.6.4      2023-12-06 [1] CRAN (R 4.4.1)
   httpuv        1.6.15     2024-03-26 [1] CRAN (R 4.4.1)
   jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.4.1)
   jsonlite      1.8.9      2024-09-20 [1] CRAN (R 4.4.1)
   later         1.3.2      2023-12-06 [1] CRAN (R 4.4.1)
   lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.4.1)
   logger        0.4.0      2024-10-22 [1] CRAN (R 4.4.1)
   magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.4.1)
   memoise       2.0.1      2021-11-26 [1] CRAN (R 4.4.1)
   mime          0.12       2021-09-28 [1] CRAN (R 4.4.0)
   miniUI        0.1.1.1    2018-05-18 [1] CRAN (R 4.4.1)
   pillar        1.9.0      2023-03-22 [1] CRAN (R 4.4.1)
   pkgbuild      1.4.4      2024-03-17 [1] CRAN (R 4.4.1)
   pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.4.1)
   pkgload       1.4.0      2024-06-28 [1] CRAN (R 4.4.1)
   profvis       0.4.0      2024-09-20 [1] CRAN (R 4.4.1)
   promises      1.3.0      2024-04-05 [1] CRAN (R 4.4.1)
   purrr         1.0.2      2023-08-10 [1] CRAN (R 4.4.1)
   R6            2.5.1      2021-08-19 [1] CRAN (R 4.4.1)
   Rcpp          1.0.13     2024-07-17 [1] CRAN (R 4.4.1)
   remotes       2.5.0      2024-03-17 [1] CRAN (R 4.4.1)
   rlang         1.1.4      2024-06-04 [1] CRAN (R 4.4.1)
   rprojroot     2.0.4      2023-11-05 [1] CRAN (R 4.4.1)
   rstudioapi    0.17.1     2024-10-22 [1] CRAN (R 4.4.1)
   sass          0.4.9      2024-03-15 [1] CRAN (R 4.4.1)
   sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.4.1)
   shiny       * 1.9.1      2024-08-01 [1] CRAN (R 4.4.1)
 P teal.logger * 0.3.0.9000 2024-11-06 [?] load_all()
   testthat    * 3.2.1.1    2024-04-14 [1] CRAN (R 4.4.1)
   tibble        3.2.1      2023-03-20 [1] CRAN (R 4.4.1)
   urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.4.1)
   usethis     * 3.0.0      2024-07-29 [1] CRAN (R 4.4.1)
   utf8          1.2.4      2023-10-22 [1] CRAN (R 4.4.1)
   vctrs         0.6.5      2023-12-01 [1] CRAN (R 4.4.1)
   withr         3.0.2      2024-10-28 [1] CRAN (R 4.4.1)
   xtable        1.8-4      2019-04-21 [1] CRAN (R 4.4.1)

 [1] C:/Users/sanchosl/AppData/Local/R/win-library/4.4
 [2] C:/Program Files/R/R-4.4.1/library

 P ── Loaded and on-disk path mismatch.

───────────────────────────────────────────────────────────────────────────────
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
@llrs-roche what if you extend the `stopifnot` to

```r
stopifnot(inherits(session, "session_proxy") || inherits(session, "ShinySession"))
```

Can you always point to lines that you refer in other package? Are those the lines in `logger`?
https://github.com/daroczig/logger/blob/bae848f08b00c3268482cabbc87e6c0da27ac720/R/hooks.R#L134-L136

Would you mind investigating how the class assertion checks should be made in `teal.logger::log_shiny_input_changes` and provide a PR? We can test a couple of apps from `teal.gallery`.

To test `teal.logger::log_shiny_input_changes` functionality you need to set

```r
options(teal.log_level='debug')
```

before you hit

```r
library(teal)
```

where the whole logging setup is made on the `onLoad`
https://github.com/insightsengineering/teal/blob/main/R/zzz.R#L1-L19

**Comment by llrs-roche** [comment]
> @llrs-roche what if you extend the `stopifnot` to
> 
> ```r
> stopifnot(inherits(session, "session_proxy") || inherits(session, "ShinySession"))
> ```
> 
> Can you always point to lines that you refer in other package? Are those the lines in `logger`? [daroczig/logger@`bae848f`/R/hooks.R#L134-L136](https://github.com/daroczig/logger/blob/bae848f08b00c3268482cabbc87e6c0da27ac720/R/hooks.R#L134-L136)

I will, I just used rstudio view function to compare the code and didn't know the lines on the repository. 

> Would you mind investigating how the class assertion checks should be made in `teal.logger::log_shiny_input_changes` and provide a PR? We can test a couple of apps from `teal.gallery`.

Yes, it is a good opportunity to explore teal.gallery a bit for inspiration. 

> 
> To test `teal.logger::log_shiny_input_changes` functionality you need to set
> 
> ```r
> options(teal.log_level='debug')
> ```
> 
> before you hit
> 
> ```r
> library(teal)
> ```
> 
> where the whole logging setup is made on the `onLoad` [insightsengineering/teal@`main`/R/zzz.R#L1-L19](https://github.com/insightsengineering/teal/blob/main/R/zzz.R?rgh-link-date=2024-11-06T11%3A52%3A58Z#L1-L19)

Ok, I'll set that on my default profile.

**Comment by llrs-roche** [comment]
The suggested checks work well but the app fails because renderPlot uses input$mean but this is not defined I assume this was changed to input$mean1 (see [line 17](https://github.com/insightsengineering/teal.logger/blob/cd9cc7e5be19c2417700308d6bdf1d8c4a55966d/R/log_shiny_input_changes.R#L17)  and [line 30](https://github.com/insightsengineering/teal.logger/blob/cd9cc7e5be19c2417700308d6bdf1d8c4a55966d/R/log_shiny_input_changes.R#L30)).
When I change the options to `options(teal.log_level='debug')` I get a more obscure error: `Error in as.loglevel.character: x %in% log_levels_supported is not TRUE` ([line 49](https://github.com/insightsengineering/teal.logger/blob/cd9cc7e5be19c2417700308d6bdf1d8c4a55966d/R/log_shiny_input_changes.R#L49)) (string must be in uppercase). 

I'll fix those in the PR.
